# Generated by Django 2.1.4 on 2018-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 char ISBN <a href="https://www.isbn-international.org/">What is ISBN? </a>', max_length=13),
        ),
    ]
